### ISSUE TITLE
Error in database city

### ISSUE THREAD

**Issue by CEric-fr** [sherpya/geolite2legacy#1]
on centos, python 2.7.5, pygeoip 0.3.2 last database (23-11-2018)
Launch : `./geolite2legacy.py -i GeoLite2-City-CSV.zip -o GeoLiteCity.dat`
Error :

```
Traceback (most recent call last):
  File "./geolite2legacy.py", line 377, in <module>
    r.load(locs, TextIOWrapper(ziparchive.open(blocks, 'r')))
  File "./geolite2legacy.py", line 118, in load
    for nets, data in self.gen_nets(locations, outfile):
  File "./geolite2legacy.py", line 214, in gen_nets
    location['subdivision_1_name'].encode('utf-8'),  # region
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
```

**Comment by sherpya** [comment]
fr?

**Comment by sherpya** [comment]
it depends on you shell locale, I've converted ft using en_US.UTF-8, I get your error using LANG=C, I'll force utf-8

**Comment by sherpya** [comment]
I updated master, new version forces utf-8 encoding, unfortunately python 2 csv reader is not unicode aware so if you need to convert non ascii entries (e.g. non english) you must opt for python3

**Comment by CEric-fr** [comment]
Python 3.6 create the same files (no diff) no test with AwStats.

Quot : the line add where removed.

**Comment by sherpya** [comment]
do awstats supports utf-8 encoded geoip database?

**Comment by sherpya** [comment]
do you have a french legacy geoip database that works correctly with awstats?

**Comment by sherpya** [comment]
I've made a database with setdefaultencoding hack, I've made a small perl snippet and the encoding looks fine:

```perl
use Geo::IP;
my $gi = Geo::IP->open("fr.dat", GEOIP_STANDARD);
my $record = $gi->record_by_addr('31.35.76.128');
print $record->region . "\n",
```
output:
Provence-Alpes-Côte d'Azur

do you have an ip that you cannot find anymore?

**Comment by sherpya** [comment]
I was wrong with csv reader, I've updated the code now it should work fine on py2 without hacks, my awstats versions sets page encoding to latin1, so I suppose you need to change something in the conf, perl does not seem to mess with locale env var when using geoip

**Comment by CEric-fr** [comment]
I use the old database from : 
http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
who don't update from 3-2018, the start of geoip2, but always accessible.
Don't no if they are french ! but they work fine with awstats, just the IP are not up to date => bad localization.

Your last version work with python 2.7.5 but still make the same .DAT file (binary compare).

Test are make on the same server, with the same conf file, just change the .DAT file before the test.

**Comment by sherpya** [comment]
So if I understand old db files were not localized (I only used English Country for myself), I suspect awstats need to be modified to handle utf-8 geoip records (I down't known about the version in master), I could use a different encoding while generating the dat but for example it fails on the letter ō.

About yout second problem (the ip lookup), could you please provide an ip address found with the old db and missing in the new one? Thanks

**Comment by sherpya** [comment]
my scripts correcly encodes names in the dat as utf8, but I suppose the format was not made with the idea of having non latin entries inside, pygeop forces latin1, geoip perl looks encoding agnostic (as the above example) so it should work as expected, but unfortunately I don't known what to check

**Comment by CEric-fr** [comment]
Just the last comment : it's not UTF8 the problem, for me, it's the region implantation in data base from V2 or to V1 !...
See comment from 26/11/2018, the content of the .TXT file create by AWStats : the old data base V1 make AWStats put a number for region and display region in web page, the convert data base from V2 make AWStats put the name of the region and dont display region in web page.
Stop testing converter because no time to spend for it... (boss say stop !)

**Comment by sherpya** [comment]
do you mean `region: Provence-Alpes-Côte d'Azur` instead of `region: A9`?

**Comment by CEric-fr** [comment]
Yes, the calculate no readable data file calculate by AWStat ("awstats[month][year].[name].txt") contain "fr_bordeaux_97" with data base maxmind V1 and "fr_bordeaux_nouvelle-aquitaine" with your converted data base from V2->V1.

In web page city render : the old data base V1 display the region (ex. line : France - Aquitaine - Bordeaux) and the converted data base display nothing (ex. line : France -  - Bordeaux).

Quote : the region are hard encode in the file "awstats/wwwroot/cgi-bin/plugins/geoip_city_maxmind.pm" : line 1177 : `"FR_97","Aquitaine",`.

**Comment by sherpya** [comment]
There is no direct mapping between maxmind ids and fips-10-4, so I'm working on a tool

**Comment by sherpya** [comment]
I've added a wip converter script for new locations to old fips codes, unfortunately the mapping is not 1:1, I'm trying to map locations to old fips region/divisions, e.g. France changed some region in 2016.
I've mapped 47k locations so far

**Comment by nethubonline** [comment]
Hi Sherpya,

After this update, previous command fails and required fips file, what is it and how to convert GeoLite2-Country-CSV.zip simply now?

`# python geolite2legacy.py -i GeoLite2-Country-CSV.zip -o GeoIP.dat`
usage: geolite2legacy.py [-h] -i INPUT_FILE -o OUTPUT_FILE -f FIPS_FILE [-d]
                         [-6]
geolite2legacy.py: error: argument -f/--fips-file is required

> 
> 
> I've added a wip converter script for new locations to old fips codes, unfortunately the mapping is not 1:1, I'm trying to map locations to old fips region/divisions, e.g. France changed some region in 2016.
> I've mapped 47k locations so far

**Comment by sherpya** [comment]
-f geoname2fips.csv, not all locations are mapped, it's a work in progress:

https://github.com/sherpya/geolite2legacy/blob/master/geoname2fips.py

contains some info about the mapping
