### ISSUE TITLE
Problem converting

### ISSUE THREAD

**Issue by jobst** [sherpya/geolite2legacy#10]
Hi
Environment: CentOS7.X, python.x86_64 2.7.5-77.el7_6, python-ipaddr.noarch 2.1.11-1.el7, python-pygeoip.noarch 0.2.6-5.el7.
Downloaded GeoLite2-Country-CSV.zip on 8/5/19
used commandline:
./geolite2legacy.py -d -i GeoLite2-Country-CSV.zip -f geoname2fips.csv -o GeoNew.dat

But got error:
Traceback (most recent call last):
  File "./geolite2legacy.py", line 219, in <module>
    class ASNv6RadixTree(ASNRadixTree):
  File "./geolite2legacy.py", line 221, in ASNv6RadixTree
    edition = pygeoip.const.ASNUM_EDITION_V6
AttributeError: 'module' object has no attribute 'ASNUM_EDITION_V6'

This even happens if I just do
./geolite2legacy.py  -h

Any help would be appreciated.

**Comment by sherpya** [comment]
your pygeoip package is outdated, anyway I've bundled the needed constants, you can safely remove system wide pygeoip, and update geolite2legacy from git

**Comment by jobst** [comment]
Hi.
Thanks, I just removed the rpm, then installed "pip install pygeoip".
Maybe in the requirments you could specify the version numbers too and hint that the pygeoip packages of some of the OS's are outdated?
Anyway, working now.

**Comment by sherpya** [comment]
Non need I've added needed constants pygeoip is not needed anymore
