### ISSUE TITLE
updated geolit2lacgay still having KeyError: 'region

### ISSUE THREAD

**Issue by jj29** [sherpya/geolite2legacy#11]
I am trying to convert a file , following your how to do having below error? can you please help?
I have all the latest file from your repo. :) 

./geolite2legacy.py -i GeoLite2-Country-CSV.zip -f geoname2fips.csv -o GeoIP.dat
Traceback (most recent call last):
  File "./geolite2legacy.py", line 447, in <module>
    main()
  File "./geolite2legacy.py", line 427, in main
    parse_fips(opts.fips_file)
  File "./geolite2legacy.py", line 358, in parse_fips
    geoname2fips[row['geoname_id']] = row['region']
KeyError: 'region'

**Comment by sherpya** [comment]
very strange, this code reads `geoname2fips.csv`, are you sure it is the file from my repo?
python version?

**Comment by jj29** [comment]
I pulled the all files again today and re-run the conversion and it worked. Thank you so much. 
Python 2.7.12.
