### ISSUE TITLE
Build time / version in DAT file comment

### ISSUE THREAD

**Issue by timelordx** [sherpya/geolite2legacy#15]
Would it be possible to use `.mmdb` file build time as a `.dat` file comment?

Right now, the comment is just a static string: `geolite2legacy.py`
```
f.write(b'geolite2legacy.py')  # .dat file comment - can be anything
```

`mmdblookup` shows `1561400523 (2019-06-24 18:22:03 UTC)`
```
# mmdblookup -v -f GeoLite2-Country.mmdb -i 8.8.8.8 | egrep '^\s+Build '
    Build epoch:   1561400523 (2019-06-24 18:22:03 UTC)
```

Or maybe if the `geolite2legacy.py` script allowed for a custom comment via a script argument, for example:
```
-c COMMENT, --comment COMMENT
```

**Comment by sherpya** [comment]
added comment from dirname in zip in 6acf333e3a075c59d70b204b15ffa13ca84c5bbd
