### ISSUE TITLE
nginx problems with dat file

### ISSUE THREAD

**Issue by sbabicz** [sherpya/geolite2legacy#4]
I do not know if this is related directly to the nginx or database transformation, but I know that lots of people will use your script for either logstash / nginx enrichment: 

When converting to .dat, nginx throws error: 
nginx: [emerg] invalid GeoIP database "/etc/nginx/geoip/GeoIP_City.dat" type:2 
nginx: [emerg] invalid GeoIP City database "/etc/nginx/geoip/GeoIP_Country.dat" type:1

**Comment by miyurusankalpa** [comment]
DAT files from this tools works fine with nginx. maybe you didn't run the commands correctly.

If you want, check the files I created using this tool in your setup. https://www.miyuru.lk/geoiplegacy

**Comment by sherpya** [comment]
@sbabicz you inverted city with country in the conf
