### ISSUE TITLE
as for REGION_IGNORE

### ISSUE THREAD

**Issue by terasawa2** [sherpya/geolite2legacy#7]
There's something I'd like to ask. Why `BOURGOGNE FRANCHE COMTE` is ignored?
https://github.com/sherpya/geolite2legacy/blob/master/geoname2fips.py#L445

In the OSS I use, there is the following source code, I expect that the region_code is `A6`, but because it is being ignored it has become `00`.

https://github.com/matomo-org/matomo/blob/ac07aa40497901c7f2a7a99166a88a1b72265d53/plugins/UserCountry/LocationProvider/GeoIp.php#L210
```
    private static function getTestIpAndResult()
    {
        static $result = null;
        if (is_null($result)) {
            // TODO: what happens when IP changes? should we get this information from piwik.org?
            $expected = array(self::COUNTRY_CODE_KEY => 'FR',
                              self::REGION_CODE_KEY  => 'A6',
                              self::CITY_NAME_KEY    => 'Besançon');
            $result = array(self::TEST_IP, $expected);
        }
        return $result;
    }
```

**Comment by terasawa2** [comment]
I just realized, the cause is that not match the region name of `fips-10-4` and Locations.csv of MMDB. isn't it?

eg:
1. fips-10-4
`Franche-Comte`
https://github.com/datasets/fips-10-4/blob/master/data/data.csv
```
FRA6	region region	Franche-Comte
```

2. MMDB Locations
`Bourgogne-Franche-Comte`
```
$ grep 3033123 ./GeoLite2-City-Locations-en.csv
3033123,en,EU,Europe,FR,France,BFC,Bourgogne-Franche-Comte,25,Doubs,Besançon,,Europe/Paris,1
```

**Comment by sherpya** [comment]
they are two different territories now, so it's directly mappable without adding any single city to one or another region, I've tried but it would take ages

https://en.wikipedia.org/wiki/List_of_FIPS_region_codes_(D%E2%80%93F)#FR:_France

**Comment by terasawa2** [comment]
Thank you so much for your lucid explanations. I get it.
```
Since 1 January 2016, it is part of the new region Bourgogne-Franche-Comté.
```
It is difficult to completely clear.
